### ISSUE TITLE
geo => "all-the-world"

### ISSUE THREAD

**Issue by icyz** [x-fran/g-trends#1]
How I can select "all the world"? I've tried to set `geo => ''`

**Comment by arikosa** [comment]
I was looking for the same thing!

**Comment by MichaelSoe** [comment]
Have you already found how to select data for the whole world? I desperately need this.

I've been debugging a bit, and when adding geo => '', the response is a 400 Bad Request. No idea why, since when looking at the code from Google itself, it should be geo => ''.

`<script type="text/javascript" src="https://ssl.gstatic.com/trends_nrtr/1328_RC04/embed_loader.js"></script> <script type="text/javascript"> trends.embed.renderExploreWidget("TIMESERIES", {"comparisonItem":[{"keyword":"bitcoin","geo":"","time":"now 1-H"}],"category":0,"property":""}, {"exploreQuery":"date=now%201-H&q=bitcoin","guestPath":"https://trends.google.com:443/trends/embed/"}); </script>`

**Comment by samuelfa** [comment]
Hi!

I just fork the component to fix this problem and I send a pull request #2 to merger with the original.

**Comment by samuelfa** [comment]
Hi again,

I generate my own component forking this one to apply the pull request with a correct version control, and I did some changes:

 - Using GuzzleHttp instead of Zend framework components
 - Avoid the use of Zend json encode/decode when PHP is giving the same tool
 - Apply style programming with PHP 7.1.

**Comment by MichaelSoe** [comment]
Hi samuelfa,

A couple of days ago, I have tested your first 2 commits to fix the problem with the empty 'geo'-variable and I can confirm that it works as it's supposed to.

I have yet to test it with the new changes, but already a very big thank you to fix this problem! You've saved my a lot of trouble.

**Comment by samuelfa** [comment]
Thank you @MichaelSoe for your words :)

**Comment by richyray92** [comment]
I too am having this issue. Any updates? Thanks this tool has been very useful to me!

**Comment by x-fran** [comment]
Untested but geo => {} should work if you want worldwide.

**Comment by Fl0ux** [comment]
I do not get it, how it is supposed to work ?

**Comment by x-fran** [comment]
If you set 'geo' to an empty string means is Worldwide. @Fl0ux
